# Generated by Django 6.0 on 2025-12-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_number',
            new_name='flight_number',
        ),
    ]
