# Generated by Django 6.0 on 2025-12-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ticket_number_ticket_flight_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_number',
            new_name='ticket_number',
        ),
    ]
